version: '3.8'

services:
  filestoring-db:
    image: postgres:16
    container_name: filestoring-db
    environment:
      POSTGRES_DB: files_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - filestoring-data:/var/lib/postgresql/data

  fileanalisys-db:
    image: postgres:16
    container_name: fileanalisys-db
    environment:
      POSTGRES_DB: files_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - fileanalisys-data:/var/lib/postgresql/data

  filestoringservice:
    build:
      context: .
      dockerfile: FileStoringService/Dockerfile
    container_name: filestoringservice
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - filestoring-db
    volumes:
      - uploads:/app/uploads
    expose:
      - "8080"

  fileanalisysservice:
    build:
      context: .
      dockerfile: FileAnalisysService/Dockerfile
    container_name: fileanalisysservice
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - fileanalisys-db
    expose:
      - "8080"

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5040:8080"
    depends_on:
      - filestoringservice
      - fileanalisysservice

volumes:
  filestoring-data:
  fileanalisys-data:
  uploads:
